### ISSUE TITLE
Shaape 1.1.0 cannot be installed using pip

### ISSUE THREAD

**Issue by pepijnve** [christiangoltz/shaape#13]
Installing shaape using pip fails because README.asciidoc is not included in the tarball but it is required by setup.py. Could a new release be created that installs correctly?

```
pip install shaape
Downloading/unpacking shaape
  Downloading shaape-1.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_travis/shaape/setup.py) egg_info for package shaape
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_travis/shaape/setup.py", line 18, in <module>
        long_description=open('README.asciidoc').read(),
    IOError: [Errno 2] No such file or directory: 'README.asciidoc'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_travis/shaape/setup.py", line 18, in <module>
    long_description=open('README.asciidoc').read(),
IOError: [Errno 2] No such file or directory: 'README.asciidoc'
```

**Comment by christiangoltz** [comment]
Thx for the report. I removed the long_description and made a bugfix release that seems to work now:

https://pypi.python.org/pypi/shaape/1.1.1
